# Site settings
title: Alex Freska
email: alex.freska@domain.com
description: "I am a creator and computer scientist who focuses on machine learning, frontend architecture, and interface design as a means to explore invention. I am currently focused on the Grapefruit project which aims to address the current shortcomings in education software and instructor-student interaction. I have worked on large web applications and through experience have become a diehard advoacate of isomorphism and immutable unidirectional state within frontend architectures.  I am an early fan of the Elixir programming language, a relative to Erlang that also runs on the ErlangVM. I believe that Elixir is the ideal tool for modern computing and scalable architectures. In my free time I explore the potential applications of convolutional neural networks in music research. I study at Rensselaer. Please contact me via Twitter."
baseurl: ""
url: "http://alexfreska.github.io/"
twitter_username: alexfreska
github_username: alexfreska

# Build settings
markdown: kramdown
permalink: :title
