# Site settings
title: Alex Freska
email: alex.freska@domain.com
description: "natural landscapes, ancient places, web, autonomous drones, ostriches, music innovation, easy solutions"
baseurl: ""
url: "http://0.0.0.0:4000"
twitter_username: alexfreska
github_username: alexfreska

# Build settings
markdown: kramdown
permalink: :title
